# What is a tensor?

A PyTorch Tensor is basically the same as a numpy array: it is just a generic n-dimensional array to be used for arbitrary numeric computation.

\begin{align*}
  \begin{bmatrix}
    1 \\
  \end{bmatrix}
  &&
  \begin{bmatrix}
    1 \\
    2 \\
    3 \\
  \end{bmatrix}
  &&
  \begin{bmatrix}
    1 & 2 & 3 \\
    4 & 5 & 6 \\
    7 & 8 & 9 \\
  \end{bmatrix}
  &&
  \begin{bmatrix}
      \begin{bmatrix}
            a & b \\
            c & d \\
      \end{bmatrix}
        &
      \begin{bmatrix}
            e & f \\
            g & h \\
      \end{bmatrix}
   \end{bmatrix}
\end{align*}


In [1]:
# understand tensors
scalar = torch.tensor(7)
print(scalar)
print(scalar.shape)
print(scalar.ndim)
print(type(scalar.item()))
print(scalar.item())

NameError: name 'torch' is not defined

In [12]:
T = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [19]:
print(T.shape)
print(T.ndim)

torch.Size([1, 3, 3])
3


In [20]:
print(T[0])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [21]:
print(T[0,0,0])

tensor(1)


In [26]:
############ Random Tensors
R = torch.rand(size=(1,3,3))

In [42]:
print(R)

tensor([[[0.7685, 0.6302, 0.7334],
         [0.3931, 0.5328, 0.5003],
         [0.1093, 0.4777, 0.3667]]])


In [34]:
############ dtype - precision
T = torch.tensor(1, dtype=torch.float32)
T

tensor(1.)

In [39]:
############ dtype, shape and device ##########
# https://towardsdatascience.com/gpu-acceleration-comes-to-pytorch-on-m1-macs-195c399efcc1
T.device

device(type='cpu')

In [41]:
############ Tensor operations
# element-wise operation:
# +, -, *, /
print(T*R)

tensor([[[0.7685, 0.6302, 0.7334],
         [0.3931, 0.5328, 0.5003],
         [0.1093, 0.4777, 0.3667]]])


In [43]:
# matrix multiplication
X = torch.matmul(R,R)
# same like X = R @ R, alias torch.mm 
# inner dimensions must match
# result has shape of outer dimensions

In [45]:
? torch.dot

In [59]:
#### tensor multiplication ?
R1 = torch.rand(4, 4, 4)
R2 = torch.rand(4, 4, 4)
R1 @ R2

tensor([[[0.7101, 0.9245, 0.3180, 1.4702],
         [0.8769, 1.4341, 0.6462, 1.6744],
         [0.6869, 1.2259, 0.5915, 1.1975],
         [0.5724, 1.2747, 0.7578, 0.8404]],

        [[0.7220, 1.7270, 1.5724, 1.9292],
         [0.4795, 1.3412, 1.5326, 1.8733],
         [0.5586, 1.4175, 1.1747, 1.5549],
         [0.3248, 0.7444, 0.4342, 0.5924]],

        [[1.4449, 1.4490, 0.7497, 0.6818],
         [0.7298, 0.8096, 0.8463, 1.0180],
         [1.1349, 1.1720, 0.9073, 0.9457],
         [0.8842, 0.8422, 0.5761, 0.4552]],

        [[1.4645, 1.1539, 0.9829, 1.1358],
         [1.5764, 1.1122, 1.1522, 1.2890],
         [0.9032, 0.7528, 0.2807, 0.5672],
         [1.3030, 1.3250, 0.8208, 0.8769]]])